import discord
from discord.ext import commands

#developer theuxie
class UnbanCog(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @commands.command(name='unban')
    @commands.has_permissions(ban_members=True)
    async def unban(self, ctx, member_id: int):
        """Desbane um usu√°rio utilizando o ID global."""
        try:
            user = await self.bot.fetch_user(member_id)
            await ctx.guild.unban(user)

            await ctx.send(f"üéâ {ctx.author.mention} Prontinho, o usu√°rio foi desbanido! S√≥ espero que ele n√£o quebre as regras novamente n√©.")

        except discord.NotFound:
            await ctx.send(
                "@nevisk/off\n"
                "Eu procurei em todo o lugar, mas n√£o encontrei nenhum usu√°rio com esse ID!\n"
                "Lembre-se, eu procuro usu√°rios por **IDs**, **men√ß√µes** e **nomes**."
            )

        except discord.Forbidden:
            await ctx.send("‚ö†Ô∏è N√£o tenho permiss√£o para desbanir esse usu√°rio.")

        except discord.HTTPException:
            await ctx.send("‚ùó Ocorreu um erro ao tentar desbanir o usu√°rio.")

    @unban.error
    async def unban_error(self, ctx, error):
        if isinstance(error, commands.MissingPermissions):
            await ctx.send("‚ö†Ô∏è Voc√™ n√£o tem permiss√£o para desbanir membros.")

        elif isinstance(error, commands.BadArgument):
            await ctx.send("‚ùå Por favor, forne√ßa um ID v√°lido.")

        else:
            await ctx.send("‚ùó Ocorreu um erro inesperado.")

async def setup(bot):
    await bot.add_cog(UnbanCog(bot))
